version: "3.4"

services:
  cuckoo:
    image: docker_cuckoo
    command: daemon
    cap_add:
      - ALL
    user: root
    privileged: true
    ports:
      - 2042:2042
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
      - ./suricata/suricata-cuckoo.yaml:/etc/suricata/suricata-cuckoo.yaml
      - ./suricata/suricata-cuckoo.yaml:/etc/suricata/suricata.yaml
      - /rooter:/rooter/
    devices:
      - /sbin/iptables
      - /sbin/ip
      - /usr/sbin/service
    network_mode: host
    env_file:
      - ./config-file.env

  web:
    image: docker_cuckoo
    ports:
      - 31337:31337
    command: web
    links:
      - mongo
      - postgres
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./config-file.env

  api:
    depends_on:
      - postgres
    image: docker_cuckoo
    ports:
      - 1337:1337
    command: api
    links:
      - postgres
    volumes:
      - ./cuckoo-tmp/:/tmp/cuckoo-tmp/
      - /cuckoo/storage/:/cuckoo/storage/
    networks:
      - cuckoo
    env_file:
      - ./config-file.env

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.5.0
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cuckoo
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.ml.enabled=false
      - xpack.watcher.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - cuckoo

  kibana:
    image: docker.elastic.co/kibana/kibana:6.5.0
    container_name: kibana
    ports:
      - 5601:5601
    networks:
      - cuckoo
    depends_on:
      - elasticsearch
    env_file:
      - ./config-file.env

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      maxCollectionSize: 33554432
      storage.mmapv1.nsSize: 32
    volumes:
      - ./mongo-data:/data/db
    networks:
      - cuckoo

  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cuckoo
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - cuckoo


networks:
  host:
    driver: default
  cuckoo:
    driver: bridge

